services:
  db:
    image: postgres:18
    environment:
      POSTGRES_USER: student_hub
      POSTGRES_PASSWORD: student_hub_development
      POSTGRES_DB: student_hub_development
    ports:
      - "5433:5432"        
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data: